services:
  juice-shop:
    image: bkimminich/juice-shop:latest
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    networks:
      - vapt-lab

  dvwa:
    image: vulnerables/web-dvwa:latest
    ports:
      - "127.0.0.1:4280:80"
    restart: unless-stopped
    networks:
      - vapt-lab

networks:
  vapt-lab:
    driver: bridge
